### ISSUE TITLE
Tracks repeatedly failing to start can freeze the bot in a loop

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#105] opened 2023-04-02 21:04 UTC
Maybe this can be fixed by moving it to a separate thread?
I will need to experiment a bit.

**Comment by 9382** [comment] 2023-06-10 18:10
Closing as wont/cant fix without proper repo
Some quick testing of radio caused no issues, so the issue is evasive/inconsistent if it still exists. But there's no reason to keep this open if we can't action on it

**Comment by 9382** [comment] 2023-06-10 18:28
What's the bloody chance I manage to find the source of the bug while screwing with the player manager just moments after I close it?

Turns out the source of the issue is the "Has this track hung" check (`float check1`) in PlayerManager freezing the bot forever if it continues to load itself over and over again, and one of the radios just happened to hang.
Rating this as High since, if there's a track that can somehow reliably hang the player manager, the bot would basically be permenantly out of service, though I don't *think* such a thing is possible

**Comment by ZeNyfh** [comment] 2023-11-07 00:05
Through some testing and magically being able to reproduce this, I think i know the root cause of the issue.
It occurs when the bot cannot send audio for some reason, a simple fix for this is ensuring the audioplayer is properly terminated when the bot leaves the vc, while also checking for network issues.

**Comment by 9382** [comment] 2023-11-07 09:15
I've been doing some looking into this, and frankly everything to do with that positionCheck is not logically sound

First of all, this check fires every time a track gets queued, not every time it plays, meaning if you play a song while another is currently queued, it does a sanity check on the currently playing song, which is not helpful in this scenario. Also, once the other song starts playing, it doesn't get checked them (I'm unsure how relevant this specific side detail is since I'm not sure at what point they get "loaded")

Second of all, it's actually been silent erroring this whole time for the first track played, since `musicManager.audioPlayer.getPlayingTrack()` wouldn't exist by the time its fired in this scenario and therefore the track doesn't even experience this check at all

@ZeNyfh We need to either purge this from the code entirely (I'm not convinced its a positive addition in its current state) or redesign it to work (don't we have a `loadFailed` method? why wasn't that good enough?)

**Comment by 9382** [comment] 2023-12-16 10:30
![image](https://github.com/ZeNyfh/gigavibe-java-edition/assets/49820045/bd847574-4201-48ee-917a-0bd0b5c480c8)
we need this fixed, come on

**Comment by 9382** [comment] 2023-12-16 13:25
Also i think it flooded the queue
![image](https://github.com/ZeNyfh/gigavibe-java-edition/assets/49820045/150f5321-7ab0-4aa9-9e40-1fc3cd352e1b)

**Comment by ZeNyfh** [comment] 2024-01-01 05:14
I looked at the code which you said caused this issue, and promptly deleted it.

However, I would like to mention that I added this code here to try and fix the bug originally, but it probably did make the issue worse. Though this raises another issue, what causes it to error other than network issues?

**Comment by 9382** [comment] 2024-01-19 21:58
> However, I would like to mention that I added this code here to try and fix the bug originally

I decided to go digging to see exactly what I could figure out about this. Turns out this code has existed before this issue was made (way before infact, seemingly as a solution to #86 - see 0a1572f) and was only in a working state for a whole 1h30m(!?) as the next commit, a101cd6, broke it for reasons I detail in my above comment (https://github.com/ZeNyfh/gigavibe-java-edition/issues/105#issuecomment-1798099333), meaning it 99%+ chance is the source of our issues here (and god knows what 86 was about since that definitely didn't fix it).

Given all the above, I'm closing this as probably fixed

**Closed by 9382** 2024-01-19 21:58 UTC
Labels: bug, Priority: Critical
